### ISSUE TITLE
Latest version doesn't work, gets many captchas wrong

### ISSUE THREAD

**Issue by a84r7a3rga76fg** [K1rakishou/4chanCaptchaSolver#10]
It is very inaccurate.

**Comment by CaptainChicky** [comment]
![image](https://github.com/K1rakishou/4chanCaptchaSolver/assets/70708832/01eb00f9-b006-452a-abc4-e4e82092cfad)
For reference, here's an example of the newer captcha

**Comment by K1rakishou** [comment]
The model has been updated.
