### ISSUE TITLE
Solver no longer reliable after latest captcha update

### ISSUE THREAD

**Issue by bungholemaster** [K1rakishou/4chanCaptchaSolver#13]
![Screenshot_20240926_061741](https://github.com/user-attachments/assets/76f3fdb7-7047-4289-bafd-ec3b86ac8965)
![Screenshot_20240926_063124](https://github.com/user-attachments/assets/4509c3f4-0dbf-4889-9a70-1a8666a73a8e)

Solver fails both new types of captcha often.

**Comment by K1rakishou** [comment]
The model has been updated.
