### ISSUE TITLE
No longer works under new captcha scaling.

### ISSUE THREAD

**Issue by Suros** [K1rakishou/4chanCaptchaSolver#3]
The font doesn't appear any different, but the size and warp do. Haven't seen a successful solution in days.

**Comment by KurubaEX** [comment]
Yes it indeed dosnt work
Anyone know any work arounds?

**Comment by aicynide** [comment]
@KurubaEX https://git.coom.tech/araragi/JKCS

**Comment by Suros** [comment]
I saw that the latest version of KurobaEX is taking model training donations. If anyone sees this, go pick it up and donate your captchas!
