### ISSUE TITLE
No longer functioning after changes to captcha formatting

### ISSUE THREAD

**Issue by Alighieri99G** [K1rakishou/4chanCaptchaSolver#4]
Seems like there have been some changes to the way that the captcha displays, now the solver doesn't work properly

**Comment by KurubaEX** [comment]
Yes it indeed dosnt work
Anyone know any work arounds?

**Comment by Alighieri99G** [comment]
Sorry, this is way outside of my wheelhouse

**Comment by aicynide** [comment]
@K1rakishou https://git.coom.tech/araragi/JKCS

**Comment by aicynide** [comment]
>In the script they do some weird voodoo shit
That's a standard HWC to WHC conversion of the input tensor, then it adds batch dimension so the final tensor is BWHC

>And also this
Thats output lebel decoder, because of CTC loss used during the model training - you need it.
There's reference implementation in java:
https://www.tensorflow.org/jvm/api_docs/java/org/tensorflow/op/nn/CtcGreedyDecoder

**Comment by aicynide** [comment]
You can also use this method to embed CTC decoder in your tfile:
https://stackoverflow.com/questions/74762668

**Comment by K1rakishou** [comment]
I have already tried all of the CTC decoder implementations that I could find and none of them helped.

**Comment by coomdev** [comment]
>voodoo shit

Maybe instead of asking ChatGPT to do the work for you, you could have just asked it how it works.

https://github.com/K1rakishou/4chanCaptchaSolver/blob/master/app/src/main/java/com/github/k1rakishou/chan4captchasolver/Solver.kt#L114

Reshaping isn't a transpose, the input image is supposed to be transposed. Have you tried visualizing what the result looks like? It's probably scrambled.

**Comment by K1rakishou** [comment]
@coomdev 
Ohh, so it had to be rotated and mirrored just like in the previous version. I see. Yeah, this was not obvious to me at all even after reading your code, jupyter notebook and chatgpt's explanations. I just looked at the input of the model in netron and it said that it's 1x300x80 so to me it was obvious that I don't need to rotate it in any way. It works now, thanks!

**Comment by coomdev** [comment]
https://github.com/K1rakishou/4chanCaptchaSolver/blob/0240aefe9a60fd4b86644a28389168f3b5252bbd/app/src/main/java/com/github/k1rakishou/chan4captchasolver/Helpers.kt#L210

@K1rakishou Here, if the image isn't 300px wide, it shouldn't be drawn in the center of the canvas but stretched to take the available space.

**Comment by K1rakishou** [comment]
@coomdev 
I don't get it. If I draw foreground image stretched to 300px then it won't be aligned with the background image anymore. Do you mean that I need to stretch the resulting image after combining bg + fg? If yes, then I'm already doing it here:
https://github.com/K1rakishou/4chanCaptchaSolver/blob/0240aefe9a60fd4b86644a28389168f3b5252bbd/app/src/main/java/com/github/k1rakishou/chan4captchasolver/Helpers.kt#L162

The problem right now is that sometimes after combining both images there are some big groups of black pixels left on the sides which are processed by the model and it sometimes sees characters in them. So from my understanding I need to somehow remove them. Here is an example:
![image](https://github.com/K1rakishou/4chanCaptchaSolver/assets/10332458/b9804a3b-9b3e-40fe-a337-a337edf0ade1)

**Comment by K1rakishou** [comment]
Nevermind I figured it out.

**Comment by coomdev** [comment]
> If yes, then I'm already doing it here
Ah, nevermind then, I misinterpreted the code.

The way we preprocessed the images was to make them display exactly as show on 4chan's captcha: the foreground image is the canvas, the background image is not visible behind, and *that* is then stretched to 300.

**Comment by K1rakishou** [comment]
Alright, hopefully this is the last set of bugfixes. 
Thanks for your help.
