### ISSUE TITLE
Was the recent update even meant to do anything new? 

### ISSUE THREAD

**Issue by XPEH69** [K1rakishou/4chanCaptchaSolver#5]
It's better than the older version after the latest captcha update a few weeks ago, but it still can't find the right slider position 25% of the time, and it can't find the right captcha code the other 50%. Even before the recent update, it'd only solve like 25% of captchas. Why not just port Dev's solver at this point? It can solve at least 50-75% of the captchas. Besides that, Ex is way better in every regard

**Comment by myilu** [comment]
Did you uninstall the previous version and install the latest?

It works great for me so far.

**Comment by XPEH69** [comment]
> Did you uninstall the previous version and install the latest?
> 
> It works great for me so far.

I just cleared, un-installed, and reinstalled the latest version again, and it works a tiny bit better, but still gets 75% wrong. It always misses a digit/number. Also, is there still no way to get the non-slider captchas with Ex?

**Comment by myilu** [comment]
Did you restart KurobaEx (better to force close it)?

>Also, is there still no way to get the non-slider captchas with Ex?

No idea.

**Comment by XPEH69** [comment]
> Did you restart KurobaEx (better to force close it)?
Of course. I cleared, uninstalled, and reinstalled the latest captcha solver several times. It partially solves the first few captchas, absolutely always getting one character wrong, and then it either always gets the slider wrong or gets most of the characters wrong

**Comment by XPEH69** [comment]
![Screenshot_2023-09-01-19-33-33-30_daf9683798e97ec54ec934cee23f7ded](https://github.com/K1rakishou/4chanCaptchaSolver/assets/125198400/7a3af8d6-5bbd-4fc8-84e4-abfe13bae2fb)
Here for example. The captcha all falls within the red circles, and it still gets it completely wrong. No amount of reinstalling the solver nor Kuroba changes how well it solves captchas. Is it just my phone, or is it something else? It hasn't gotten a single captcha correct since the update

**Comment by K1rakishou** [comment]
Can you copy a captcha json that doesn't work and post it here?

**Comment by XPEH69** [comment]
> Can you copy a captcha json that doesn't work and post it here?

{"challenge":"ecqBeR3qidXSaYGM.2064c71286e7c1ea65ebb0d7fc542d1cad51d79723f4106a14369dede296dd07","ttl":120,"cd":4,"img":"iVBORw0KGgoAAAANSUhEUgAAASwAAABQAgMAAADehKDoAAAACVBMVEUM9wzu7u4AAADaU1i0AAAAAXRSTlMAQObYZgAAB3lJREFUWIWVmE+rGzcQwGUTB+LTo3QLza2HQLKfwg0NND5tlpWI95SEuqT6FI9QF\/pOIUShfSdvyBbvfMrOH\/1d+6XU8N6utKOfRiPNaCSl81+r7\/4BVF\/5Sj+VFzr4Ggrc4\/\/B6pFlRnyx4zlr6g8Xqr\/Cqh5pRy\/uTNBOPZweXUJE2cjaM2stPZsLTZ73MM2qZl1GlmUWnI1i759G7+s5y5SvnrXzep1y0WbAf6Nv0GtwL7KP3aHA3jJrn7S1UCgNyDJgRFU72vxbV4rybCkR3dG\/Fs5Zegp6wZ++mmXM4Kv9uEkZlY25vsQK9noDIKMyLNPi\/yfaLyF6Yn2+JuqHOaupYGored\/T+Hl9WdEEh9jJVIQW3edTznrU56zrFUS3scw6YeudaGLwW7FE+m8BirVKtt898x\/VgtxG5h31aiCsL+dZxZzjcgKVLSDdD9rZH6X4UikW5xlmmTZTpJ2huELpIIC6Y5iYJq9phywSZx8UmS42N3MUGns4FXrRAF6rimR1oxQbl\/Qy8\/hhwoyb6Cft8FLNpFCfihUJLO7izHkAPq6k71g1Bh9Kq+wnRUJ7vVFqHW1Nui9K2HGxSyCqmTzLpMXQKOkwsbyxgh3lc3ut7D85C93VS3yKVVdqMWM538f38lyIA1+r\/rYYej+d2SuwlFLLKqvfqAf+OQpafZcMT+7cnrM2ibXIxoTlpYssS+WKNW5Ch23mQ75yzmoWkeWfFemBy8\/bdRVYmQ8lRsHaSLFL9ZUvr\/Jm5O6R1ZGsiSxqq8q2Kmdkz0Do41vjG93Bws\/08vwSa\/eaCWbO6mYsavMissxE5ZOUF6HZb7JvJtZGOrrAuve3Zz3CNUQM8uvGzyuxfoUZy9v6Amv9t3SFffUHZiGs8fMqrBOFgO6\/WNQmsV5oYcGpidOsFg+xnO2PevIsb2N+0guxbqvA0p71EY6Jtb59BxyUAusXarsTxiqxuiOxYJWzlhi8umuvP7Fs1ResbEyqTiwrLHDEujd0Az0pEG4S6wG4luPMRdYQWO2J2lCaQcXl0I\/CqiKLTOMo2meszD6qxl6kLPpE1vizvsC6j1PI4f+rrO9A5yzl55OUENbesyjVu4v1R2AZatN61uKMNRHrG2KRXS6zYOTyGnqaLxPtpceSNT7Hx1NmYbahJChOr0qWY1Y9sF6RdYq23zNr+4WW5dNjYlHUfnO8yJL+kTUIy3oW1MyyuFerBa63VWA5\/Uz3zHpi9gVrNWOB9fbC3EFYICw4grA6dPN+ptcY7Feygu1rIDtqZt5b\/k5wYVHOEVg7z4LAUhlrUesVs6aWWT28Y5bT28SCMbBsYB1LvU7MWvWHgjUZrL9aHmhsgXXjol6vZix6dN4+y9EKC1MxZh0wr1QbYqHpRmF9xpyPjanbY8n6kOxCe6+tRC\/jWdSXsGphUUrnWR0Ia6w9S+IUClDblduL7QdKJ1AOQ\/NmodZJr4bCpGc9hPfCCmO+eZ+zQvwatKEyJdYlCwUH1I1sa25Hsf3YetaWWN05i74vKTZs7s1YLrD+4jiG8NbbD66weutZy0PrmDUKC925u77KWUOfWHrG2g5Yvo\/LG8hO64MNLLLBEp3PHq9U\/aeJ80isdtqk\/RFZvwoLDrSnPfNrt3Y\/6FyvCZfAcaOqGo8PwuI8tq2yfRtZRmJ2TSy2PbF+8Pslba0bZmE9suDTSCzMC42cNkqWxH9Di5m8QVj++6o+sPh62sJhRy6O4cHCPyON8eA3DxdZk7DqxKKyccZxTuJZtH8TiwJgw3qFn+zpgcU5JjnqtSLDwrdsL+t6nw++ZBZmK+hZ0n6Vnd19Xsj7cmR9gasFsyoqOqieE2vyrIHy6XXSJr75FL9kwUj5amDpk+SJjhI3tEBFDvz4AsteYp3YGOix6NTIqvKcs6b91WQHo8Tal6yNNwir3FLQruqqq7pGUmD8DsKKSf7uQk6+2sLJCSudnHACcZHX1bZbJ1ZFrCoOTBWHGmFpOE3Mys91ZkHn8eqtfivlZimsIUr0Kh0epAmOBdN+TgJqV4xeF4fGbi3nvnSOMXO9zBFZ1ZYXY+2rAsvZIZPECXGYWe5TjSp6xoaUdVKHdK71VfHjGWsXCvvEyn9kl4KVN9dbfy+SnW2DBROrCXZ7pmt+5a21+G010CqkUzP+mXD5IXciidXVEPX\/UVibdc7CQTjAw\/te9DKsl3T\/1kLOWnPQ9z8rMk2ds3Br\/3jzKb9bimPcQsbiSxBh0WkEvW\/Yc22l4+F8TzcmxYiN793W0JasQz3wDZjj\/Zwx7LtnVwAZi2evrYNanvWZ7gMn5+dfshZker26SmT7BOpQ9MD9YDbyLmOxrJ1+C4K1k5uycB1o\/RNksPh7Kl6I7\/0H+BismO4Lp7jwsEddJR16KwVxPcuTHj06v3\/LWJklgiSLbT2r06LL0\/yOySS1dLwbusjSnvU6K1IWtEqeFQzALHfG0tsZ6yb5YRuUCvGlzVmBX05+TrZpHRuI14ahhr7RvV\/v7mJlkcNaiCZJTkg\/Uukl2Z6U3N2pV6YWZCZB1qcQKCSw9TcHT9X\/AhYTcq7iwODpAAAAAElFTkSuQmCC","img_width":300,"img_height":80,"bg":"iVBORw0KGgoAAAANSUhEUgAAAV0AAABQAQMAAACArzSeAAAABlBMVEUAAADu7u6BVFV4AAAGdElEQVRIiX2XPY\/kxBaGj8fDeiWk8ZJ1sNraf8BkO+iiqUEEE96fANImN6NFwDRi6fJoEEvWZBCstEj3Z1xE16glOrm6Q4hE4Bp1QALYoxXbhnbXue8p2\/01Cw66\/fH4rfec+jomLph5yetjzH91VMRT\/NWfrm+N\/g6+uK1cdOfFLgxlvyMx7U4ut5wBxtu1YZ5vwLhVGjmZbcIGMK+UxxtNVOF3UyEoB93wim4RbqIIemYH7qKD7KK7b14R4EVjg9d4eyi+nfDpNgxDi7Wy3oGLv1KWi3QH5m14Ox7VCobWFtvwktvEdAG3npseqrbhquPW+WuVeVd5zj90FpZ8+xB2voKnIlirV3CrUNepy0XQ68V2jK35oLHId7KxDS5bSyoMmptbqesC6I7K4GIcDC46eLwNz1ZBIpcu2NbcZSOcbrQ+5z9MYyo03xlcj+erlWHpmVKt3l2NxLVnnwqDBy5YgNfm5XyjScDLFpb\/F8y2sfKi9TbahtEZZhkSX0gwDYw5uAzKz3eUcza1aeCbPMAyYdP6bAX\/HDLUTlhRVqNxMVuM\/nTIxWzBH54vZ9qbBv4MqZ9XprUhc36sCmd+mjme6tj5R6U51daE0eLpZ\/5eZwJnMoEKCbFw+qZwnnT0K3\/oh2\/ieZg7JSWe3ibAdczXTZ+IsmNX0VvwVqKHAaNP\/GxCcUUkcHXBpQ7ZHBcO3eUu7VGAvdYZop77Q9WLLy2RquiPSS1LFbJcf+DQK3bk7t4XmIc6k\/DrUlevjxykK1rMamp6qk6dBKMdPVjn1ic16SoeO9rvD0SZKl2NBP7mH4CbIVKewcfXJ7gAXJK5vnw2EM819XT5gHWdZEfCzSxyUMbsD+\/+S9t93MnIzK6+HBxRtVcT6cyXut4jsWEmdoi4Ipz2B4lNxWVpJotsIK4B30+807U48HSWWHFygcSXLUwpJ7yCD5V3D5nPxeH7SuArwLocpAIPiZ7Ay+Au0JrSExblexGGM\/UF9lfZezXW6wDfu09PFNcBfkbphF\/yQuDc0iC2GpmxpwF26bM9dPUg\/jH2gKN9SrGeOf2yF\/HF9\/T+I5vUx2nVKPt0P8ng7dF\/6WM4jnoCv3Tm817076eeiG3k0dECl6mPeqlDVIicRJkQLDwP7\/SiLPIUC59pjivNlyMmSmxNMb+g6AvJBakp4P6d3hsZHQO2fUeaxfO5jM+9uD6O8R+FxKUFusud3OndI4HZIleaPwCM9JQZYeJfdPDTMkV3ub2DBk7YGopkfr7djwOsavMUHaAkwIpSUT446MGRJpUDxqzEZO6nmKWAS\/M8b2CTEb3GQ3d80IssYd4pgW8CrGAlw8hho7zAfA44qVcwGbOCSTKCGRB7bVjmFhIFeOkBDwAfYzTZ9xr4kGIoEy0vZClr4YcIigEfRf+jB2TQoPvkGvBRAz\/Mn8pC28I6ygVO70dXGeDyxJSY5tw\/zGBjQfqBkhHdwFa\/jkS5YarO2QK+tNoqp\/1A0ykGoNU9mLgc7Z9a8pFVySY8TCf6l6hMsG7QY6wcVkU1JkJ+8Dgjr2yKwWoEztj2aCDzxM4tllw6oXfZpmmtKpPvn2DMsI0V+6V7kghM9I5MWofl3LRwrGplOU+swC6NPd+4J6MGDjukVSFbBNihYfWFznUDq5iLuTM53rcyhEQ55YVne4KsO4VkfGsm3CljN3BYzyu5IfVgWNvReB\/hivKsxiJfNsrX2AidYVVhvoYVaSh7idcTpo8IyjlWQyuupvybcWga8FeV\/kbgnIepbDxmyvZxCeVRHWBLBXaMWuAzpOC7hwJj3uQCVxja7\/BszNIPAQ47uIR0ihPvPgf8PJc9FA81lGWHlTezRYAXYSt0E9kyr70yXrebHxYIeyZ3c1nWGuW25grljSu89tJsuLlka7p1urWxUb8U7p9yFVIBtJKwG1asOlHW6z3XpbILS7NzjBeM1BYOggKzGYcbN03PyeMxNk7+fVNZB3hdIcyfB1gONb26DJ47OEg42qji8gCj5pn\/Jy+aOruDpRCaB2W1rkDKVNzcVF2dJDXPuLXYeB53VTtGWqO88ib6SavcwLxRUq6+DVaN1atqtyt7ljPePbr3fR4a8Fu16JbicrOQ6p6+oggMili2gurmA\/8KeBH2cdM815vwEXUKufyHHyl1Wsnbystgaj0+iu1iv\/limfLmR42I4iQveNq+136k4LFq4f8D1F+y5iZ3BPoAAAAASUVORK5CYII=","bg_width":349}

**Comment by XPEH69** [comment]
> Can you copy a captcha json that doesn't work and post it here?

And here's the image of the captcha itself
![Screenshot_2023-09-01-20-08-04-15_daf9683798e97ec54ec934cee23f7ded](https://github.com/K1rakishou/4chanCaptchaSolver/assets/125198400/8e95820d-3390-4f5d-8c8c-4ca14183ebe9)

I've tried everything from reinstalling the solver and solver, clearing data, checking/unchecking settings and whatnot. It actually tries doing something unlike after they changed the captcha, but it's never gotten a single one correct

**Comment by K1rakishou** [comment]
Works for me. You are most likely not using the latest version. Uninstall the current one and install this one https://github.com/K1rakishou/4chanCaptchaSolver/releases/tag/v2.1

![Screenshot_20230902_105440](https://github.com/K1rakishou/4chanCaptchaSolver/assets/10332458/0eec6e39-d455-46ce-ba21-f280af4b56f2)

**Comment by XPEH69** [comment]
Re-downloaded it and had to reinstall it a few more times to get it to work, but it works great now.
