### ISSUE TITLE
4chan tweaked their captcha, so it no longer works

### ISSUE THREAD

**Issue by MCorbo7** [K1rakishou/4chanCaptchaSolver#9]
![IMG_20231218_214427](https://github.com/K1rakishou/4chanCaptchaSolver/assets/84733317/e00c7821-505d-48e6-983a-c6e5c0900579)

**Comment by XPEH69** [comment]
On the KurobaEx thread, he said to turn on solved captcha donation. He'll get to it eventually

**Comment by lux5am** [comment]
Yeah none of the captcha ever works since a few weeks. Either fail 1-3 letters or entirely wrong. The  letters not even that hard to read.

**Comment by K1rakishou** [comment]
Ok I have updated the model.

**Comment by MCorbo7** [comment]
Thank you, can confirm it works perfectly again!

**Comment by lux5am** [comment]
> Ok I have updated the model.

Thank you sars
